#!/bin/bash -e

dac_upd()
{
	V=`i2cget -y 1 0x48 "$1"`
	V=$(( (V & ~$2) | $3 ))
	i2cset -y 1 0x48 "$1" "$V"
}

### R0 System Registers
dac_upd 0 0xff 0x00  # 00000000 clock gear MCLK=XIN
#dac_upd 0 0xff 0x04 # 00000100 clock gear MCLK/2=XIN
#dac_upd 0 0xff 0x08 # 00001000 clock gear MCLK/4=XIN
#dac_upd 0 0xff 0x0c # 00001100 clock gear MCLK/8=XIN

### R1 Automatic input selection
#dac_upd 1 0xff 0x0c # 00001100 automatically select serial/DSD/SPDIF
#dac_upd 1 0xff 0x08 # 00001000 automatically select serial/SPDIF 
dac_upd 1 0xff 0x04 # 00000100 automatically select serial/DSD
#dac_upd 1 0xff 0x03 # 00000011 only DSD
#dac_upd 1 0xff 0xe1 # 11100001 only SPDIF
#dac_upd 1 0xff 0x00 # 00000000 only serial

### R2 serial Data and Automute
#dac_upd 2 0xff 0xfc # 11111100 AUTOMUTE_CONFIG_MUTE_THEN_GND and I2S
dac_upd 2 0xff 0x3c # 00111100 Automute off

### R5 Automute Level 
dac_upd 5 0xff 0x68 # 01101000 default

### R6 Deemphasize filter and Volume ramp rate 
dac_upd 6 0xff 0x4a # 01001010 default

### R7 Filter Bandwidth and System Mute 
#dac_upd 7 0xff 0x40 # default 1000000
dac_upd 7 0xff 0x02 # 50k@44.1 00000010

### R8 GPIO-1_2 Config 
#dac_upd 8 0xff 0x88 # default 10001000
dac_upd 8 0xff 0x80 # automute status 10000000

### R9 GPIO-3_4 Config
#dac_upd 9 0xff 0x88 # default 10001000
dac_upd 9 0xff 0x18 # lock status 00011000

### R10 Master mode and Sync config
dac_upd 10 0xff 0x10 # 128fs enabled 00010000
#dac_upd 10 0xff 0x00 # 128fs disabled 00000000
#dac_upd 10 0xff 0x8a # master on D_CLK=MCLK/2 128fs disabled 10001010

### R12 Jitter Eliminator / DPLL Bandwidth
#dac_upd 12 0xff 0x5a # default 01011010
dac_upd 12 0xff 0x00 # DPLL off 00000000
#dac_upd 12 0xff 0x00 # Lowest BW 00010001
#dac_upd 12 0xff 0x00 # Highest BW 1111111

### R13 Jitter Eliminator 
dac_upd 13 0xff 0x20 # enable (default) 00100000
#dac_upd 13 0xff 0x00 # disable 00000000

### R14 Soft start
dac_upd 14 0xff 0x8a # default 10001010

### R15 GPIO Input and Volume Config
#dac_upd 15 0xff 0x0d # stereo modei,ch1 mapped to DAC1 00001101
#dac_upd 15 0xff 0x09 # stereo 00001001
#dac_upd 15 0xff 0x01 # default on start  00000001
dac_upd 15 0xff 0x07 # Frank's recommend (stereo/all_to_use_ch1/vol_ctl_enabled) 00000111

### R16 Volume 1-8
dac_upd 16 0xff 0x00 # default 1010000

### R17 Volume 1-8
dac_upd 17 0xff 0x00 # default 1010000

### R18 Volume 1-8 
dac_upd 18 0xff 0x00 # default 1010000

### R19 Volume 1-8
dac_upd 19 0xff 0x00 # default 1010000

### R20 Volume 1-8 
dac_upd 20 0xff 0x00 # default 1010000

### R21 Volume 1-8 
dac_upd 21 0xff 0x00 # default 1010000

### R22 Volume 1-8 
dac_upd 22 0xff 0x00 # default 1010000

### R23 Volume 1-8
dac_upd 23 0xff 0x00 # default 1010000

### R24 
dac_upd 24 0xff 0xff # default 1010000

### R27  
dac_upd 27 0xff 0x7f # default 

### R32_DEFAULT 
dac_upd 32 0xff 0x00 # 

### R37 Programmable FIR Config 
#dac_upd 37 0xff 0x00 # OSF enabled
dac_upd 37 0xff 0x80 # OSF disabled 10000000

### R38 DAC 1-2 Mapping 
dac_upd 38 0xff 0x10 # default 00010000
#dac_upd 38 0xff 0x00 # all ch1 00000000
#dac_upd 38 0xff 0x11 # all ch2 00010001
